### ISSUE TITLE
How does the center update?

### ISSUE THREAD

**Issue by leyuan-sun** [rssalessio/PytorchRBFLayer#1]

**Comment by rssalessio** [comment]
Hi @rginjapan , when you create an RBF layer you can set if the center is a learnable parameters (or not).

Check the parameters of RBFLayer [here](https://github.com/rssalessio/PytorchRBFLayer/blob/03300c60f0ddb08de0c7846b03e70297d071e420/rbf_layer/rbf_layer.py#L75) 
By default the parameter `constant_centers_parameter` is set to false, which means that the centers are treated as learnable parameters (therefore automatically updated whenever you perform backpropagation).
